### ISSUE TITLE
Stealth knife kills

### ISSUE THREAD

**Issue by AliLogic** [oscar-broman/samp-weapon-config#133]
Since the library negates and syncs the stealth knife kills/ neck slits,  in TDM servers,  this is a huge issue.  This should be resolved to allow such stealth knife kills if a server wants to allow it under certain criteria.

**Comment by ADRFranklin** [comment]
It doesn't negate damage done by knife kills. I have them on my server and they work fine. I don't know why you think they don't? 

If they don't for you it's probably due to your script. If you feel this is not related to your script then please provide a minimal example of code that can be used to reproduce the issue.

**Comment by AliLogic** [comment]
I don't feel like it, but I will still look into it asap and respond back.

**Comment by AliLogic** [comment]
#134 This should fix it imo.  Haven't tested it.

**Comment by AliLogic** [comment]
Yes, this fixed.  I tested it with my staff team.

**Comment by AliLogic** [comment]
Fixed as of my PR merge.
