### ISSUE TITLE
setcbugallowed

### ISSUE THREAD

**Issue by ChrissX7** [oscar-broman/samp-weapon-config#156]
Hello! Using a command with the following, it works correctly on my PC, there is no problem but if I use it on the VPS (Debian) this command does not work properly. It doesn't work.

SetCbugAllowed(false, playerid);

OR 

SetCbugAllowed(true, playerid); 

I've tried it many times and there's no way it's going to work on the VPS. This is weapon-config (the include works perfectly in the VPS)

I was going to use it a lot for various systems but I see that it doesn't work well, on my pc everything is going well

**Comment by ADRFranklin** [comment]
Pawn code can not be influenced by any OS. So if it works on one, it will work the exact same on any machine that can run the Pawn VM.

It seems to me, you might have made a mistake in your setup.

**Comment by ChrissX7** [comment]
> Pawn code can not be influenced by any OS. So if it works on one, it will work the exact same on any machine that can run the Pawn VM.
> 
> It seems to me, you might have made a mistake in your setup.

So what is the correct setup?

**Comment by ADRFranklin** [comment]
I have no idea what you are working with right now. So it's hard for me to give you any clear instructions that may be worthwhile.

I would suggest joining the sa-mp discord (https://discord.gg/hURGKHJ) and asking me in there, then I will be able to have a conversation with you about your setup.

Since this isn't a weapon-config issue.

**Comment by ChrissX7** [comment]
What is your discord name?

**Comment by ADRFranklin** [comment]
JustMichael#7884
