### ISSUE TITLE
_inc_y_iterate ERROR

### ISSUE THREAD

**Issue by ZeeRik** [oscar-broman/samp-weapon-config#157]
I use this 
https://github.com/Open-GTO/foreach

And I get it
#error the YSI library is required, get it here: github.com/pawn-lang/YSI-Includes

**Comment by ADRFranklin** [comment]
Yes, because that library is outdated. Since the majority of developers use YSI, I am now forcing the use of `y_iterate`. 

Foreach is based on an old version of `y_iterate` but it's very outdated and doesn't take advantage of the many optimisations that have been made over the years.

Please use YSI, and instead use `y_iterate`

**Comment by Chaprnks** [comment]
I definitely agree with ADR. Foreach hasn't been updated in years & I doubt it's even cross compatible with the latest YSI 5 y_iterate. It takes some time to get used to the complexity of YSI.. but once you get the hang of it.. you'll never script without it!

**Comment by ZeeRik** [comment]
Of course, I understand you, but I think that it is wrong to force the use of YSI.  Many do not need this.
