### ISSUE TITLE
Healthbar loses its dimensions

### ISSUE THREAD

**Issue by noSmoke98** [oscar-broman/samp-weapon-config#165]
Hello, 
I've noticed that on screens of small resolution Your healthbar loses its dimensions. So, in some cases it's noticeable that the default healthbar shows up underneath. 
I have tried to prevent it and it was done successfully. I used "LD_SPAC:white" (font 4) which works based on pixels. After this was done, the healthbar acts the same on all screens (just like the default GTA healthbar).
![usebox_vs_ld_spacwhite](https://user-images.githubusercontent.com/68742727/88407708-ce86fa00-cdd2-11ea-8773-b538ca107624.jpg)

**Comment by ADRFranklin** [comment]
This is something that can be looked at. I'd prefer it if it didn't make it look really washed out and try to keep the traditional colours the game already offers if possible.

If not, then it would need to be something that everyone can agree on.

**Comment by zile42O** [comment]
@ADRFranklin i think with sprites this can be solved cause, i was have some shitty problems like this with boxes and switch  to sprites. This is very important, because it should not at least look like a cube. So @noSmoke98 is right, i agree with him.  
Example: http://prntscr.com/tq2x68 (this is spirtes, like noSmoke but diffrent design for my needs, and  works very well on small resolutions)
@noSmoke98 Odavno sam to hteo da updateam al moram da cekam na ove ostale da se smiluju..

**Comment by tr1xy** [comment]
@zile42O don't you dare compare Balkan's SA-MP "community" (which is made out of little toxic kiddos and idiots) to the English/Spanish... SA-MP community where people appreciate the game itself and where people don't play it because they're forced to (Balkans have potato pcs smh)

Also don't use Serbian language here, it's not proper to do so because they cannot understand what you wrote cuz the most important parts will be lost in translation (especially the last kinda insulting one).

You're welcome to fork this repository if you do not like it this way and adjust it for your own needs (welcome to the Github!), many people here appreciate the game older than you, not just the aesthetics some RPG pay2win "server" "developers" would do...

@Xunder-Matth forked this repo for the biggest Balkan SA-MP server and changed everything he doesn't like to adjust it for Balkan players, is that hard for you or you're dumb to do so or something like that...? 🤔

**Comment by zile42O** [comment]
@tr1xy i am really sorry because your comment is deleted, but still I saw the notification that arrived in the mail, and saw your comment, so your comment has nothing to do with this issue, nor the content of this issue, I don't know what you tried to say, but I'm here a Contributor, and I have the right to say what I think(and everyone), it is my duty to do what is needed to improve this code, if my pull request is good and needed, there are people who will review it here and accept.
In this case the conversation is on the topic of health bar, to prevent changing the width of the bar, or height, depending on the resolution of the players. And why you mention my friend Xunder? Thats is not clear to me, and why you mention me at all because of that kind of nonsense, it is not clear to me either. Thanks for the nice comment, enjoy.

**Comment by tr1xy** [comment]
![IMG_20200813_215358](https://user-images.githubusercontent.com/56768635/90180606-85adda00-ddaf-11ea-81f8-027702a645e4.jpg)
Why is your sensei talking about you like this, contributor sama?

**Comment by tr1xy** [comment]
You were really disrespectful (on your language) about people who appreciate the game and don't play it for the aesthetics (yes, they don't like aesthetics and they have right to say No to this if they want, personally I added this in my local version of this include ages ago but they have full right to reject this if they want...)...

Also I mentioned how Xunder has his own version of this include (addons and fixes), that's why I mentioned him but your English is like Bangladeshi Tech Support scammer or even worse so you did not understand, not my problem)

I'm pretty sure that you could normally comment without using such words.

**Comment by zile42O** [comment]
Ino mi je rekao da nije mislio na mene nego na sadasnjeg collabolatora mani se decko vise, svo vreme sam na insta s njim, nisam te dirao ni nista, slike imam poslacu ti ako hoces mozemo call discord/messanger i da popricamo nije problem.

**Comment by zile42O** [comment]
Dodaj me zile42O#3192 ne ujedam

**Comment by tr1xy** [comment]
Use English, be respectful towards others because TL API for 3rd world counties is very bad and everything is lost in translation, please.

Here in Serbia, we use "moram da cekam na ove ostale da se smiluju.." as an insult or I misunderstood?

It's sounds like you're saying that they're dumb/wrong because they don't want to change it because they prefer the original colors or what...?

Sorry if I misunderstood (hint: Here I'm giving you a chance to say that I misunderstood you so we can stop this needless comments) but most probably I didn't.

**Comment by zile42O** [comment]
Nah thats not insult, and don't be good here and  so much respectful,  come on discord tell what u want.

**Comment by Jprimero15** [comment]
Its even more worse on android
