### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Makan13** [oscar-broman/samp-weapon-config#179]
Hello,
I was urged to change line 5522 of the include to
`public OnPlayerDamage(playerid, Float:amount, issuerid, weapon, bodypart)`
Because of my custom gamemode

But now when i try to compile this error happens:

> error 025: function heading differs from prototype

This is the function of my gamemode
`public OnPlayerDamage(playerid, Float:amount, issuerid, weapon, bodypart)
{
	if(issuerid != INVALID_PLAYER_ID)
	{
        if(InEvent[playerid] == 1 && InEvent[issuerid] == 1)
        {
            if(eInfo[Headshot] == 1)
            {
                if(bodypart == 9) SetPlayerHealthEx(playerid, 0);
            }
        }
        if(InAmmu[playerid] == 1)
        {
            new Float:issuerHP, Float:playerHP;
            GetPlayerHealth(issuerid, issuerHP);
            GetPlayerHealth(playerid, playerHP);
            GameTextForPlayer(issuerid, "NO KILLING!", 3000, 3);
            SetPlayerHealth(issuerid, issuerHP-20);
            SetPlayerHealth(playerid, playerHP+20);
        }
        AbuseTick[playerid] = gettime();
	}
    return 1;
}`

I hope you can help me!

Regards

**Comment by ADRFranklin** [comment]
There should be no need to change the include what so ever, if you feel it doesn't work for you, and you have certain you have understood it's use and are using it correctly, then you can report the issue here. 

If you modify the include, then I can't really help you as I don't really know what you modified. As for the code you posted I'm unsure as to what you are trying to accomplish. It looks like you have modified a public function in the include, which you don't need to do, and now you have broken it.

**Comment by Makan13** [comment]
Oh hey, thank you for your response, i repaired the include and understood that i was using a wrong function.
`public OnPlayerDamageDone()` should have been used.
have a nice day!
