### ISSUE TITLE
Blood

### ISSUE THREAD

**Issue by Crayder** [oscar-broman/samp-weapon-config#23]
0.3.7 __RC2__ Object ID: 19836

Attach that to the player if he died from bullets, vehicle collision, explosions, and other blood causing death when he is for sure on the ground.

**Comment by oscar-broman** [comment]
Is it the particle that automatically finds the ground and makes a blood pool (like the default one)?

Otherwise I suppose animations and Z velocity could determine whether he's on the ground.

**Comment by Crayder** [comment]
Actually it's just an object not a particle effect.

**Comment by oscar-broman** [comment]
So it would look strange unless they're standing on a flat ground?

The best solution would be to use MapAndreas or ColAndreas to determine the angle of where they're standing and rotate the blood properly. This include could do this, obviously with a `#define` to enable it.

I can't see any other way that would be almost flawless.

**Comment by Crayder** [comment]
Well setting the animation already has the strange look your describing when they die anyways, so would it absolutely matter?

**Comment by oscar-broman** [comment]
The animations probably look strange on slopes more steep than 35°, but the object looks strange even on slopes more steep than 15°, which is a lot more common. Besides, it's not possible (afaik) to apply the animations with the player ped rotated. Perhaps the sync data could be spoofed to achieve that.

**Comment by Crayder** [comment]
So basically the best way to achieve the correct X/Y angle would be getting a triangle with either MapAndreas or ColAndreas (which I wish was released :3).

**Comment by oscar-broman** [comment]
I think something like this could be nice to have, but due to the plugin dependency it should exist as a separate include (which is possible with this API).

If you make such an include, I will add a link in the documentation. Getting some extensions for this include would actually be rather cool. If you need functions or modifications done to facilitate the process of making such an extension, create an issue or submit a pull request.
