### ISSUE TITLE
Knife "exploit"

### ISSUE THREAD

**Issue by Zbyss** [oscar-broman/samp-weapon-config#238]
Client can spoof `OnPlayerGiveDamage` with 0.0 knife damage and insta-kill every player on the server.
There are no checks if the player even has a knife, has it as an armed weapon, if attacked player is streamed or any delay between knife kills.

Proof: https://streamable.com/tc6vjd
(first client has disabled textdraws, but damage given textdraw is also visible there)
![image](https://user-images.githubusercontent.com/49686333/154063929-7029332c-a8db-4701-ad36-9560c8559122.png)

**Comment by criticalerror99** [comment]
Yes my server was attacking by SobFoX and by this method. I think it's important to fix this immediately.

**Comment by NexiusTailer** [comment]
Shouldn't this be limited to range checks for melee weapons? By this check:
https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L4661-L4670
ProcessDamage, in turn, is called from OnPlayerGiveDamage:
https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L3246

**Comment by ADRFranklin** [comment]
https://github.com/oscar-broman/samp-weapon-config/blob/6432ea41c877da8c29e9157200ab4f48a62b92d6/weapon-config.inc#L3239

Moving the within streaming distance of player, above the knife stuff, should prevent all players on the server being hit by this. Ofc an additional check should be made to make sure the player doing the damage is within distance of the player as well as actually having a knife.

**Comment by Zbyss** [comment]
There also needs to be a check on the player state, as currently the player can kill anyone spectating him.
https://streamable.com/4l17ed

**Comment by NexiusTailer** [comment]
@Zbyss Does it have any practical sense? I mean, a spectating person spawns immediately after this kind of "death" after this damage or not? If it is, then this may concern not only knife damage, but in any other as well.

**Comment by Zbyss** [comment]
@NexiusTailer Yes, the spectator spawns like after a regular death. I have no idea if it's relevant also to the other weapons, because they can't be simply spoofed by sending GiveDamage packets. Probably something like a Damager would work, but I have no idea how to test it on a spectator.

**Comment by NexiusTailer** [comment]
I finally found time to check and fix all currently relevant problems (including unsolved part of this one) and can say that GiveDamage cannot be spoofed for any weapon (including knife damage) for this reason:
https://github.com/oscar-broman/samp-weapon-config/blob/9f6f2b7e497e1a8eca6b8facc5ea72cec83b868b/weapon-config.inc#L3223

`WC_IsPlayerSpawned`, in turn, have this check:
https://github.com/oscar-broman/samp-weapon-config/blob/9f6f2b7e497e1a8eca6b8facc5ea72cec83b868b/weapon-config.inc#L1033

So, if player sends GiveDamage not being in onfoot/driver/passenger state, this will be blocked. However, a cheater can still send TakeDamage being in spectating just like you said before and this will be fixed in coming PR with some other minor improvements.
