### ISSUE TITLE
Bugs and suggestions

### ISSUE THREAD

**Issue by zeelorenc** [oscar-broman/samp-weapon-config#24]
Hey, great plugin - well done! First and foremost, testing on latest 0.3x.

**Bugs**

1. Class selection fails unless it's death by a car or something client-side.

2. Fall damage is just not as accurate as before?

3. Is the death world thing necessary? It seems to inflict bugs than anything else.

**Suggestion**

1. Allow users to easily disable portions of the code with using #define instead of using functions (Toggle{function}(bool: value)

    Should stop compiling unnecessary code that is already disabled by the server. Example:

    ```
#define TOGGLE_DAMAGE_FEED (true)

#if TOGGLE_DAMAGE_FEED == true
 ... operations ...
#endif
```

2. Make an addition to this by introducing maybe another optional feature which enables users to access weapon data (GetWeaponDamageFromDistance, GetWeaponDamage, GetWeapon blah blah.)

3. When the include is stable, it might be great if this was merged altogether with the SKY plugin. (As that plugin really has only things relevant to this include.)

**Comment by codectile** [comment]
What do you mean by "Fall Damage" ? Elaboration will be very nice, though.

**Comment by zeelorenc** [comment]
Just slap yourself 10M in the sky and compare damage from with and without the new weapon config include.

**Comment by codectile** [comment]
Test Results:

**Condition 1:** Without weapon-config.inc

`Height: 20 sa-mp units`
`Damage: 37.0-38.0` (Two observations)
`Average Damage: 37.5`


**Condition 2:** With weapon-config.inc

`SetCustomFallDamage` set to `false`
`Height: 20 sa-mp units`
`Damage: 37.46-39.41` (Two observations)
`Average Damage: 38.435`


**Condition 3:** With weapon-config.inc

`SetCustomFallDamage` set to true`
`Height: 20 sa-mp units`
`Damage: 0.0-0.0` (Two observations)
`Average Damage: 0.0`

**Comment by Crayder** [comment]
Wait, so yours failed with custom damage toggled on? You know that doesn't add up to well, do you even have custom damages set for the fall damage @codectile? Or do you have it set to  0 on purpose...? It seems pretty accurate to me though, and the class selection thing does not affect me because I use y_classes. But it should be fixed for everyone else.

**Comment by oscar-broman** [comment]
1. I think this can be fixed by quickly switching to spectate mode before spawning.
2. The custom fall damage is W.I.P. and should be considered experimental.
3. I've yet to experience any bugs with it, and it even works with filterscripts. The reason for it is to make sure the bodies of paused/lagging players disappear at the exact moment they are set to respawn.

1. Maybe, but it would make the script messy as it would be needed inside many callbacks.
2. Sure.
3. SKY is not exclusively used by this include, and it has quite a few areas it's useful in even if the damage system is not used.

**Comment by codectile** [comment]
@Crayder I did not edit a single thing and for your information I used the original version not the forked one.

**Comment by Crayder** [comment]
That has nothing to do with what i asked. When you toggle custom fall damage you have to set the fall damage in the SetCustomFallDamage parameters. If you don't it will be 0. I don't need any information, I was just checking your testing procedure.

**Comment by codectile** [comment]
Sorry for misinterpreting your comment. Here's what inside `OnGameModeInit()`, `SetCustomFallDamage(true);`.

**Comment by Crayder** [comment]
Thats why the damage was 0, so your test results were viable. 

	SetCustomFallDamage(true, 40.0, -0.75); // Mine is ', 25.0, -0.5'.

**Comment by codectile** [comment]
It isn't working with the specified height `20 sa-mp units`.

**Comment by Crayder** [comment]
It's the velocity, it never reaches the threshold in a 20 meter drop. Try lowering the threshold:

SetCustomFallDamage(true, 40.0, -0.1);

**Comment by codectile** [comment]
Still the same result.

**Comment by Crayder** [comment]
SetCustomFallDamage(bool:toggle, Float:damage_multiplier = 25.0, Float:death_velocity = -0.6);

Enable debug messages to see what you get, raise the multiplier. -0.1 should kill you easily, see what the debug says your velocity is.

**Comment by codectile** [comment]
I've already tested by raising the multiplier by 30.0
![debug](https://cloud.githubusercontent.com/assets/8154609/6430299/b5bc9f46-c029-11e4-85b4-d722b5ba6a88.png)

**Comment by Crayder** [comment]
So it's not detecting the impact..? Sorry I can't test now, but why does it think you're velocity is 0? Of all the problems here, that's the oddest.

**Comment by codectile** [comment]
It just displays the damage but health loss does not takes place. I guess, I got another bug. I am not sure.

When a player just jumps off a building he dies immediately while in air. `SetCustomFallDamage(true, 70.0, -0.1);`
![debug](https://cloud.githubusercontent.com/assets/8154609/6430319/c2af266e-c02a-11e4-8d3f-56761824f454.png)

**Comment by Crayder** [comment]
When the debug is showing OnPlayerTake and nothing else it's because OnPlayerTake is not detecting anything to cause any further damage. The fall was not being detected. Now, you multiplied the damage received in OnPlayerTake by 70.0 and instantly killed if their damage was less than -0.1. It's only supposed to check the velocity after impact, and it's only supposed to damage on impact. So somehow it is detecting impact mid-air for you, right?

**Comment by codectile** [comment]
Try to test it. You will get to know what is happening and yes, it is as soon as the fall gets detected the player dies immediately.

**Comment by Crayder** [comment]
It doesn't happen to me.

``SetCustomFallDamage(true, 25.0, -0.5);``

**Comment by codectile** [comment]
I was talking about this `SetCustomFallDamage(true, 70.0, -0.1);`

**Comment by Crayder** [comment]
I know, I was saying just saying that it should not be detecting the fall in midair.

**Comment by zeelorenc** [comment]
Do 10.0 metres, not 20.0.

**Comment by Crayder** [comment]
Like I said before, this bug does not affect me. I can jump from the top of the US Bank tower and it only detects ground impact. Just out of curiosity, are you jumping (like jumping UP and then falling down) or just dropping off? In my super power script something interesting happens when I add velocity that may be relating to your bug...

**Comment by zeelorenc** [comment]
Dropping off, that's primarily the issue lol

**Comment by zeelorenc** [comment]
@oscar-broman, any progress? I want to fork it but I want to ensure I don't waste my time just incase you already are at a near complete stage

cheers

**Comment by oscar-broman** [comment]
I have been very busy the last couple weeks, and I will be busy for another week. After that I'll have time to dig into this.

**Comment by Crayder** [comment]
Nice to hear, I check my notifications for this like every other day... :P

**Comment by zeelorenc** [comment]
Alright, I'll see what I can do and recommend any options

**Comment by oscar-broman** [comment]
Alright, I made some issues from this so they can be tracked individually.

**Bugs**

1. #25
2. Custom fall damage is still work in progress. Make issues for specific problems (such as #21, #17, #6, #4).
3. Make an issue with a bit more info, as I'm unable to find any issues with it.

**Suggestions**

1. #26
2. #27
3. Will not happen, as described above.
