### ISSUE TITLE
Modified weapon.dat

### ISSUE THREAD

**Issue by KirovNoName** [oscar-broman/samp-weapon-config#289]
what native code that detects modified weapon.dat

**Comment by SysadminJeroen** [comment]
You can probably use AverageShootRate to detect changes in weapon.dat that changes the shooting rate.

I'm pretty sure that the damage modifications are just ignored by weapon-config, since it handles damage in a different way.
I'm not even sure if damage modifications is something even sent in the netcode, other than with weapon-config.

**Comment by NexiusTailer** [comment]
> what native code that detects modified weapon.dat

Basically this one:
https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L570-L626
