### ISSUE TITLE
Enter vehicle when performing death animation

### ISSUE THREAD

**Issue by forss** [oscar-broman/samp-weapon-config#33]
http://forum.sa-mp.com/showthread.php?t=563387&page=12

 Originally Posted by KubiPL View Post
There is a bug. When you're death and you press enter vehicle key near vehicle, your death is aborted.Animations get cleared and you can move while in dying state.

Perhaps locking all the vehicles for the player before OnPlayerDeath would solve this. Could you make an issue of this on GitHub please? And I will look into it.

**Comment by oscar-broman** [comment]
@Crayder, @codectile, @zeelorenc do you guys have any experience with vehicle params? Could this be done easily or will hooking some vehicle functions be required?

**Comment by Crayder** [comment]
Couldn't you just hook OnPlayerEnterVehicle and check to see if the player is dead or not?

**Comment by oscar-broman** [comment]
Are you sure? I thought that only happens because people use SetVehicleParams in OnPlayerEnterVehicle. It should be in OnPlayerDeath, before the player has pressed F.
And the real issue is that the animation looks ugly. Setting position on death should only happen if the player currently is entering a vehicle.

**Comment by Crayder** [comment]
When the player is lying on the ground dead, s_IsDying is true. When OnPlayerEnterVehicle is called and s_IsDying is true for the player they shouldn't be entering the vehicle so we don't allow it (by setting the position).

**Comment by Crayder** [comment]
Also I came across a bug while investigating. If you die while on a bike (maybe in cars too), the game still thinks you're in the vehicle (radio is still playing, but I did fall off the bike and die).

**Comment by Y-Less** [comment]
Could you set TogglePlayerControlable false, so they can't press enter in the first place?

**Comment by oscar-broman** [comment]
The camera would be froze, which is undesired.

**Comment by KubiPL** [comment]
By locking vehicle, you can only disable animation on entering as driver, but not as passenger.
Solution is to set player pos or animations OR use function, which toggles player moving without camera. I had seen this somewhere, but is it real?

**Comment by codectile** [comment]
Sorry for being late, I was inactive for few days. @oscar-broman We will just set a repeating timer (`SetTimerEx("Fix", respawn_time, true, "i", playerid)`) as soon as the player dies, consisting of a `ClearAnimations` function and kill the timer after the `respawn` time , this procedure will freeze the player without affecting the camera.

The pseudo-code, would be:

```pawn

forward Fix(playerid);
public Fix(playerid)
{
    if(!death_animation) ClearAnimations(playerid);
    return 1;
}
```

**Comment by oscar-broman** [comment]
Doesn't that make the player stand up every 5ms?

**Comment by codectile** [comment]
How would he stand up every 5 ms ?

**Comment by Crayder** [comment]
You would also need to repeatedly set the facing angle in that timer, current I can spin while dead.

**Comment by codectile** [comment]
The spinning problem is there since the release.

**Comment by Kar2k** [comment]
You guys are taking the approach wrong about locking vehicles.

It's a good thing I just created a complex animation system for my cnr, despite my players hating it but I love it :)

KubiPL seems to have the answer, but what? Passenger entry does get locked out too.

EDIT2: I just seen that you mentioned locking the vehicles, this won't work because the player will still get up to attempt entry.

Wrong!

Locking a vehicle makes the player doesn't even try once they are in an animation that is FROZEN!

Here's a piece of my 'stickup' code from my server. Where 2 players enter a stickup which only uses animations and I had to find a way to cancel vehicle entry.

ClearAnimations(id, 1);
    ClearAnimations(playerid, 1);
    SetPlayerToFacePlayer(id, playerid);
    SetPlayerToFacePlayer(playerid, id);
    playAnimation(id, "ROB_BANK", "SHP_HandsUp_Scr", 4.0, 0, 0, 0, 1, 0, .stoppable = 0, .gameAnimation = 1);
    playAnimation(playerid, "PED", "gang_gunstand", 4.0, 1, 0, 0, 1, 0, .stoppable = 0, .gameAnimation = 1);

NOTE: FREEZE argument, make sure the animation is FROZEN. (just replace playAnimation with ApplyAnimation and remove stoppable and gameAnimation). If they are not frozen, CERTAIN animations (and I mean CERTAIN) will allow you to enter the vehicle.

for(new vehicleID = 1; vehicleID < MAX_VEHICLES; ++vehicleID)
	{
		if(!IsValidVehicle(vehicleID)) continue;
    	SetVehicleParamsForPlayer(vehicleID, playerid, 0, 1);
    	SetVehicleParamsForPlayer(vehicleID, id, 0, 1);
	}

**Comment by oscar-broman** [comment]
Could you change them into `ApplyAnimation`? I have no idea what you meant in that comment.

**Comment by Kar2k** [comment]
http://wiki.sa-mp.com/wiki/ApplyAnimation
freeze Setting this to 1 will freeze the player at the end of the animation. 0 will not.

Lock every vehicle in the server for the player, plus under OnVehicleStreamIn.

There.. issue fixed.. nobody can enter vehicles anymore.
