### ISSUE TITLE
GetPlayerPos problem for AFK players

### ISSUE THREAD

**Issue by Catalin-Mihai** [oscar-broman/samp-weapon-config#50]
I noticed that if i kill a player who is AFK, his coordinates are the same with the old ones after his respawn. Can this be fixed somehow? 
I think it can be done by saveing the position of the player after OnPlayerSpawn and hook GetPlayerPos to return these values.
Thanks!

**Comment by oscar-broman** [comment]
Do you mean that his location is the same while he is between being dead and spawned?

GetPlayerPos should not be used if the player is dead. Pretending a player is somewhere he still is not would be a bad idea, imho, because many scripts use SetPlayerPos in OnPlayerSpawn, which would be impossible to predict by this include.

**Comment by Catalin-Mihai** [comment]
I understand. I thought it could be "fixed". It's annoying when i use a command like "/goto" and the targetID is not there.

**Comment by oscar-broman** [comment]
You should check if `GetPlayerState` returns `PLAYER_STATE_WASTED`, and show an error.

If you want to do the behavior you describe, you could modify the include to add `GetSpawnInfo` (and make a pull request!).

See this function:
https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L1555
You also need to make sure it works both with SetSpawnInfo and normal player classes. Look at the behavior here:
https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L2276

You'd just need to make the reverse of that.
