### ISSUE TITLE
Hooking OnGiveDamage with y_hooks

### ISSUE THREAD

**Issue by spacemud** [oscar-broman/samp-weapon-config#61]
Is this possible? I gave it a go but the hooked callback wasn't called.

For the time being I'm using ALS, but it would be great if I could use y_hooks instead.

**Comment by Y-Less** [comment]
If you want to try fixing this yourself, the problem* is here:

https://github.com/oscar-broman/samp-weapon-config/blob/9359ccd7682d9b0b7d64b2e874d8a9febd8e57e5/weapon-config.inc#L5341

And similar lines for other callbacks.  That will call `OnRejectedHit` directly (I couldn't find `OnGiveDamage`), it won't call the function via `CallLocalFunction`.  In some ways this is slightly better, because it means the code is faster, but `CallLocalFunction` looks the function address up by name at run-time, and it is that process that y_hooks hijacks to redirect to the hooked functions.  If you were to replace that line with:

```pawn
CallLocalFunction("OnRejectedHit", "iai", playerid, s_RejectedHits[playerid][idx], E_REJECTED_HIT);
```

It might work.  If it doesn't, it is because `CallLocalFunction` expects all arrays to be immediately followed by their length (for memory allocation reasons) hence the `ai` and `s_RejectedHits[playerid][idx], E_REJECTED_HIT`; whereas `OnRejectedHit` does not take that third parameter.  It should still work though because extra parameters are just ignored.

\* I say "problem", but it is more of a small incompatability between the two systems, not the fault of either one individually.  However, I have just come up with another way of doing y_hooks that would solve this issue in the general case, by replacing the first few instructions of a function with a jump to the hook stub instead of replacing the address in the AMX header.

**Comment by Y-Less** [comment]
The other downside to this method is that if `OnRejectedHit` isn't used in a mode, the code to call it won't be output either.  Thus even with the new preamble rewriting method I came up with y_hooks wouldn't work at all.

**Comment by rt-2** [comment]
Can't we just add a "CallRemoteFunction" in weapon-config? I mean, those who wants to hook some OnPlayerTakeDamage.
It is true that it would be easier for includes.

**Comment by Y-Less** [comment]
Your best bet is actually an uncommon feature called *prehooks* - code specially designed to be called before y_hooks hooks, which themselves come before ALS hooks and the default callback.  Going back to my `OnRejectedHit` example, that callback is called directly, not via `CallLocalFunction` because the code in the file must be called before any hooks, so this is a prime candidate for making a prehook.  The setup for these is a little awkward, but fully stand-alone and fast:

```pawn
// Generic setup - can be done multiple times in different includes.
#if !defined CHAIN_ORDER
	#define CHAIN_ORDER() 0
#endif

#define CHAIN_HOOK(%0) forward @CO_%0();public @CO_%0(){return CHAIN_ORDER()+1;}

#define CHAIN_NEXT(%0) @CO_%0

#define CHAIN_FORWARD:%0_%2(%1)=%3; \
	forward %0_%2(%1); \
	public %0_%2(%1) <_ALS : _ALS_x0, _ALS : _ALS_x1> { return (%3); } \
	public %0_%2(%1) <> { return (%3); }

#define CHAIN_PUBLIC:%0(%1) %0(%1) <_ALS : _ALS_go>

// weapon-config sepcific setup - include the states and insert in to the chain.
static stock _WC_IncludeStates() <_ALS : _ALS_x0, _ALS : _ALS_x1, _ALS : _ALS_x2, _ALS : _ALS_x3> {}
static stock _WC_IncludeStates() <_ALS : _ALS_go> {}
CHAIN_HOOK(WC)
#undef CHAIN_ORDER
#define CHAIN_ORDER() CHAIN_NEXT(WC)
```

Using this actually becomes simpler:

This:
```pawn
	#if defined WC_OnRejectedHit
		WC_OnRejectedHit(playerid, hit);
	#endif
```

Becomes:
```pawn
	WC_OnRejectedHit(playerid, hit);
```

This:
```pawn
#if defined _ALS_OnRejectedHit
	#undef OnRejectedHit
#else
	#define _ALS_OnRejectedHit
#endif
#define OnRejectedHit WC_OnRejectedHit
#if defined WC_OnRejectedHit
	forward WC_OnRejectedHit(playerid, hit[E_REJECTED_HIT]);
#endif
```

Becomes:
```pawn
#if defined _ALS_OnRejectedHit
	#undef OnRejectedHit
#else
	#define _ALS_OnRejectedHit
#endif
// " = 1" is whatever the default return value is.
#define OnRejectedHit(%0) CHAIN_PUBLIC:WC_OnRejectedHit(%0)
CHAIN_FORWARD:WC_OnRejectedHit(playerid, hit[E_REJECTED_HIT]) = 1;
```

Just make sure you use a consistent `WC` prefix in all these bits (or whatever prefix you want).  y_hooks has explicit code for detecting and accounting for these prehooks, without requiring you to include y_hooks at all.  The nice thing is that because of the `CHAIN_ORDER` macros, as long as your dependencies are included first, they will be called first.  You also no longer need compile-time checks that the callbacks exist as the default state handler takes care of that.

One last thing that is required, in your `OnScriptInit` function (whichever one you use) put:

```pawn
state _ALS : _ALS_go;
```

This can be set many times by many includes, it just must be set.  I have no figured out how to make this the default value.

**Comment by TamerGezici** [comment]
After Michael rebased the script I went ahead and updated the include. I died to a vehicle explosion and this is what I got:

[24/05/2020 18:25:35] [debug] Server crashed while executing AVTTDM.amx
[24/05/2020 18:25:35] [debug] AMX backtrace:
[24/05/2020 18:25:35] [debug] #0 native CallLocalFunction () in samp-server.exe
[24/05/2020 18:25:35] [debug] #1 000469c0 in OnPlayerDeath (playerid=0, killerid=65535, reason=51) at D:\coding\PAWN\avttdm\pawno\include\weapon-config-fh.inc:2645
[24/05/2020 18:25:35] [debug] #2 00018c68 in public OnPlayerDeath (0, 65535, 255) at D:\coding\PAWN\avttdm\pawno\include\YSI_Data\y_foreach\..\..\YSI_Coding\y_hooks\..\y_cgen\y_cgen.inc:127
[24/05/2020 18:25:35] [debug] Native backtrace:
